services:
  postgres:
    image: postgres:17-alpine3.22
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=test
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    networks:
      - prod

  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - prod


volumes:
  pgdata:
  prometheus:

networks:
  prod:
    driver: bridge
