name: CI.yml
on: [push, pull_request]
jobs:
  Docker_files_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check docker-compose.yml
        run: docker compose config --quiet